"""add tags column to catalog items

Revision ID: da2aad34b9e3
Revises: b33e4d6a4e9e
Create Date: 2025-09-06 16:37:26.060500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da2aad34b9e3'
down_revision = 'b33e4d6a4e9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_items', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_items', 'tags')
    # ### end Alembic commands ###
